# Generated by Django 5.0.6 on 2024-08-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Criminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("crime", models.CharField(max_length=200)),
                ("jail_location", models.CharField(max_length=100)),
                ("cell_no", models.IntegerField()),
                ("health_condition", models.TextField(blank=True)),
            ],
        ),
    ]
